[package]
name = "shadow-cloud-companion"
version = "0.16.1"
description = "Shadow Cloud Companion"
authors = ["Shadow-Cloud"]
edition = "2021"

[lib]
name = "shadow_cloud_companion_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-single-instance = "=2.4.4"
shadow-cloud-companion-engine = { path = "../engine" }
tokio = { version = "=1.52.3", features = ["sync", "time", "macros"] }
reqwest = { version = "=0.13.4", default-features = false, features = ["rustls", "json", "system-proxy"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
